version: '3'

services:
  api:
    build: ./api
    networks:
      - boilerplate-network
    ports:
      - 8000:8000
    command: python manage.py runserver 0.0.0.0:8000
    env_file: .env

  client:
    build: ./client
    networks:
      - boilerplate-network
    ports:
      - 3000:3000
    depends_on:
      - api
    command: npm start
    env_file: .env
    stdin_open: true

networks:
  boilerplate-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
