version: '3'

services:
  api:
    build: ./api
    networks:
      - boilerplate-network
    ports:
      - 8000:8000
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000
    env_file: .env
  
  client:
    build: ./client
    networks:
      - boilerplate-network
    ports:
      - 3000:3000
    depends_on:
      - api
    command: npm start
    env_file: .env
    stdin_open: true
  
  db:
    image: postgres
    networks:
      - boilerplate-network
    ports:
      - 6543:5432
    env_file: .env
    volumes:
      - ~/data:/var/lib/postgresql/data

networks:
  boilerplate-network:
    driver: bridge
